name: CI/CD on Gummy-Dang server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build -x test

      - name: Make directory / Copy Jar file
        if: github.event_name == 'push'
        run: |
          mkdir -p deploy
          cp ./build/libs/*.jar ./deploy

      - name: Create zip file
        if: github.event_name == 'push'
        run: zip -r ./gummy-dang.zip ./deploy
        shell: bash

      - name: Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secretes.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload zip file to S3
        if: github.event_name == 'push'
        env:
          BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws s3 cp --region $AWS_REGION ./gummy-dang.zip s3://$BUCKET_NAME

